### ISSUE TITLE
Errors in "Installing Homebrew taps and extensions" in generated bash.sh

### ISSUE THREAD

**Issue by giovannidl** [platanus/strap#3]
When running bash.sh generetad by strap failed with the next output:

> --> Installing Homebrew taps and extensions:
> Error: Your Homebrew is outdated. Please run `brew update`.
> !!! Installing Homebrew taps and extensions: FAILED
> !!! Run '/Users/gio/Documents/strap.sh --debug' for debugging output.
> !!! If you're stuck: file an issue with debugging output at:
> !!!   https://github.com/platanus/strap/issues/new

Then, when I run `brew update` it said brew was already updated.

To resolve the issue I removed Homebrew with
`ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"`
[reference](https://superuser.com/a/203740)

And then install Homebrew with
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
[reference](https://brew.sh/index_es.html)

Then I could run the previous bash.sh without problems.

**Comment by blackjid** [comment]
when you run the `bash.sh` file, was brew already installed?

**Comment by giovannidl** [comment]
No the first time

**Comment by blackjid** [comment]
mm, I think I'll update the project from the upstream strap, to see if there are some improvements..., but is difficult to test because you usually only run strap once. :) 

I'll keep the issue open to let other so add their two cents.
